baseURL = 'https://rogi52.github.io/blog/'
languageCode = 'ja'
title = 'My New Hugo Site'
theme = 'hugo-theme-stack'

relativeURLs = false
canonifyURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  mainSections = ["posts"]
  math = true
  customCSS = ["css/custom.css"]