name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # main ブランチに push したら自動実行

permissions:
  contents: write  # GitHub Pages に push する権限

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ソースをチェックアウト
      - uses: actions/checkout@v4

      # Hugo をセットアップ
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      # Hugo サイトをビルド
      - run: hugo --minify --config hugo.toml --baseURL 'https://rogi52.github.io/blog/'

      # public ディレクトリの中身を確認
      - run: ls -R ./public

      # public ディレクトリを gh-pages ブランチにデプロイ
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
